<?php
    $order = $block->getOrder();
    $orderCustomAttributes = $order->getData('ecomteck_order_custom_attributes');
    $attributes = json_decode($orderCustomAttributes, true);
?>
<?php if($attributes):?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?php /* @escapeNotVerified */ echo $block->getTabTitle(); ?></span>
        </div>
        <div class="admin__page-section-content">
            <?php if(isset($attributes['before-shipping-address-fields'])): ?>
                <?php foreach($attributes['before-shipping-address-fields'] as $key => $code):?>
                    <div class="admin__page-section-item order-payment-method">
                            <div class="admin__page-section-item-title">
                            <span class="title">Info</span>
                        </div>
                        <div class="admin__page-section-item-content">
                            <strong>Seller Code:</strong>
                            <span class="price"><?php echo nl2br($block->escapeHtml($code));?></span><br/>
                        </div>
                    </div>
                <?php endforeach?>
            <?php endif ?>

        </div>
    </section>
<?php endif; ?>

